version: '3.4'

services: 

  elasticsearch:
    image: elasticsearch:7.9.0-oss
    container_name: elasticsearch
    privileged: true
    #network_mode: host
    ports:
    - 9200:9200
    networks:
       network:
          ipv4_address: 10.10.10.3
    volumes:
      - ./conf/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./conf/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
    logging:
        driver: "json-file"
        options:
           max-size: "10m"
           max-file: "2"

  onos:
    image: onos:2.7
    restart: always
    container_name: onos
    #network_mode: host
    ports:
      - 38181:8181
      - 38101:8101
      - 6653:6653
    networks:
       network:
          ipv4_address: 10.10.10.5
    privileged: true
    #mem_limit: 4g
    environment:
      - "ONOS_IP=10.10.10.5"
      - "ES_HOSTS=${ES_HOSTS_IP:-10.10.10.3:9200}"
      - "JAVA_OPTS=-Xms4G -Xmx4G -XX:+UseConcMarkSweepGC -Dds.lock.timeout.milliseconds=10000"
      - "ONOS_APPS=drivers,org.onosproject.openflow"
    volumes:
      - /etc/localtime:/etc/localtime
    logging:
        driver: "json-file"
        options:
           max-size: "10m"
           max-file: "2"

networks:
    network:
        driver: bridge
        ipam:
          config:
             - subnet: 10.10.10.0/24

